from pathlib import Path

from app.core.config import (
    MARKDOWN_OUTPUT_DIR,
)
from app.core.logger import app_logger


class MarkdownWriter:
    """
    Generate markdown architecture reports.
    """

    def __init__(self) -> None:
        pass

    def generate_report(
        self,
        repository_name: str,
        detected_stack: dict,
        architecture_result: dict,
        graph_summary: dict,
        repository_summary: str,
        architecture_diagram: str,
    ) -> Path:
        """
        Generate markdown report.
        """

        app_logger.info("Generating markdown report...")

        markdown_content = self._build_markdown(
            repository_name=repository_name,
            detected_stack=detected_stack,
            architecture_result=architecture_result,
            graph_summary=graph_summary,
            repository_summary=repository_summary,
            architecture_diagram=architecture_diagram,
        )

        output_path = MARKDOWN_OUTPUT_DIR / f"{repository_name}_architecture.md"

        output_path.write_text(
            markdown_content,
            encoding="utf-8",
        )

        app_logger.success(f"Markdown report generated: {output_path}")

        return output_path

    # md template
    def _build_markdown(
        self,
        repository_name: str,
        detected_stack: dict,
        architecture_result: dict,
        graph_summary: dict,
        repository_summary: str,
        architecture_diagram: str,
    ) -> str:
        """
        Build markdown report.
        """

        languages = detected_stack.get(
            "languages",
            {},
        )

        frameworks = detected_stack.get(
            "frameworks",
            [],
        )

        patterns = architecture_result.get(
            "patterns",
            [],
        )

        return f"""
# Architecture Analysis Report

---

## Repository

`{repository_name}`

---

## AI Repository Summary

{repository_summary}

---

## Detected Languages

{self._format_dict(languages)}

---

## Detected Frameworks

{self._format_list(frameworks)}

---

## Architecture Patterns

{self._format_list(patterns)}

---

## Dependency Graph Summary

- Nodes: {graph_summary.get("nodes")}
- Edges: {graph_summary.get("edges")}
- Density: {graph_summary.get("density")}

---

## High-Level Architecture Diagram

{architecture_diagram}

---

## Generated By

AI-Powered Codebase Architecture Analyzer
"""

    # utils
    def _format_list(
        self,
        values: list,
    ) -> str:
        """
        Format list as markdown bullets.
        """

        if not values:
            return "- None"

        return "\n".join(f"- {item}" for item in values)

    def _format_dict(
        self,
        values: dict,
    ) -> str:
        """
        Format dictionary as markdown bullets.
        """

        if not values:
            return "- None"

        return "\n".join((f"- {key}: {value}") for key, value in values.items())
